In [1]:
import numpy as np

In [2]:
arr = np.array([1 ,2 ,3] )
arr2 = np.array([4 ,5, 6])

In [4]:
np.concatenate([arr ,arr2])

array([1, 2, 3, 4, 5, 6])

In [7]:
np.concatenate([arr ,arr2] ,axis = 1) # tek boyutlu arrayler zaten tek satırdadır :D

AxisError: axis 1 is out of bounds for array of dimension 1

In [8]:
arr3 = np.array([[1 ,2 ,3],
                [4 ,5 ,6]])

In [9]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr.ndim

1

In [14]:
arr3 = np.concatenate([arr3 ,arr3]) 

In [15]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [16]:
arr3.ndim

2

In [17]:
arr3 = np.concatenate([arr3 ,arr3] ,axis=1)

In [18]:
arr3

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [19]:
arr3.ndim

2

In [26]:
arr4 = np.array([[1 ,2 ,3],
                [4 ,5 ,6]])

In [27]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.concatenate([arr4 ,arr4] ,axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

In [30]:
np.concatenate([a ,b ,c])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.concatenate([a ,b ,c] ,axis =1) # 1 boyutlu dizilerde axis = 1 kullanılmaz !

AxisError: axis 1 is out of bounds for array of dimension 1

In [50]:
array1 = np.array([["a" ,"b" ,"c"],
                  ["d" ,"e" ,"f" ]])

In [51]:
array1

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [52]:
array2 = np.array([[1 ,2 ,3],
                  [4 ,5 ,6]])

In [53]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
con1 = np.concatenate([array1 ,array2]) #ayrı ayrı birleştiler

In [55]:
con1

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['1', '2', '3'],
       ['4', '5', '6']], dtype='<U11')

In [56]:
con2 = np.concatenate([array1 ,array2] ,axis=1) #sutunları kendi içinde birleştirdi

In [57]:
con2

array([['a', 'b', 'c', '1', '2', '3'],
       ['d', 'e', 'f', '4', '5', '6']], dtype='<U11')

# not = her sutunun eleman sayısı eşit olmalıdır
