In [1]:
import numpy as np 


In [2]:
a = [1 ,2 ,3 ,4]

In [3]:
arr = np.array(a)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
arr2 = np.array(a ,dtype="int")

In [7]:
arr2

array([1, 2, 3, 4])

In [8]:
arr3 = np.array([1.3 ,1.2 ,1 ,2] ,dtype="float")

In [9]:
arr3

array([1.3, 1.2, 1. , 2. ])

In [10]:
np.full((3,5) ,3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

# 0 dan 31 e kadar 3 er 3 er artan array oluştur


In [11]:
np.arange( 0,31 ,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

# sıfır ile bir arasında 10 adet sayı oluştur

In [12]:
np.linspace(0,1 ,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# dağılımı belirli sayı üretme


In [15]:
np.random.normal(10 ,4 ,(3,4))

array([[10.65387836, 12.66115696, 13.8050272 , 12.62091788],
       [ 2.3383155 ,  3.55774592, 11.17121067,  7.41182409],
       [11.28210775, 16.08504021, 10.27555645,  4.9724596 ]])

# 3'e,3 üçlük bir matris oluşturup  , 0 ile 10 arası sayı üretme

In [17]:
np.random.randint(0,10 ,(3,3))

array([[0, 5, 7],
       [9, 1, 9],
       [2, 1, 5]])