In [1]:
import numpy as np 

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr = np.arange(1,10)

In [12]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr2 = arr.reshape((3,3))

In [10]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr.ndim

1

In [15]:
arr2.ndim

2