In [16]:
import numpy as np 
import pandas as pd 
from sklearn.linear_model import Ridge ,Lasso
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split ,cross_val_score
from sklearn import model_selection
import matplotlib.pyplot as plt
from sklearn.linear_model import RidgeCV ,LassoCV ,ElasticNet


In [9]:
df = pd.read_csv("Hitters.csv")
df = df.dropna()







In [10]:
dms = pd.get_dummies(df[["League" ,"Division" ,"NewLeague"]]) 
#bagımsız değişkenlerin bazılarını sayısal değer yapma 
dms

League_A  League_N  Division_E  Division_W  NewLeague_A  NewLeague_N
1           0         1           0           1            0            1
2           1         0           0           1            1            0
3           0         1           1           0            0            1
4           0         1           1           0            0            1
5           1         0           0           1            1            0
..        ...       ...         ...         ...          ...          ...
317         0         1           1           0            0            1
318         1         0           1           0            1            0
319         1         0           0           1            1            0
320         1         0           1           0            1            0
321         1         0           0           1            1            0

[263 rows x 6 columns]

In [11]:
y = df["Salary"] #bagımlı değişken maas
y

1       475.0
2       480.0
3       500.0
4        91.5
5       750.0
        ...  
317     700.0
318     875.0
319     385.0
320     960.0
321    1000.0
Name: Salary, Length: 263, dtype: float64

In [12]:
x_ = df.drop(["Salary" , "League" ,"Division" ,"NewLeague"] ,axis = 1).astype("float64")
#bagımsız degisken leri cektik 

In [13]:
x  = pd.concat([x_ , dms[["League_N" ,"Division_W" ,"NewLeague_N"]]] ,axis = 1)
# bagımsız degiskenleri birleştirdik 

In [14]:
x_train ,x_test , y_train , y_test = train_test_split(x , y 
                                                     ,test_size = 0.25
                                                     ,random_state= 42)
# veri setimizi test ve egitim setlerine ayırdık


In [17]:
enet_model = ElasticNet().fit(x_train ,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 8487984.799367314, tolerance: 3898.686956380658
  positive)


In [18]:
enet_model.coef_

array([ -1.86256172,   8.70489065,   5.10426375,  -2.89875799,
        -1.28642985,   5.24343682,   6.04480276,  -0.14701495,
        -0.21566628,  -0.7897201 ,   1.80813117,   0.80914508,
        -0.61262382,   0.26816203,   0.27172387,  -0.36530729,
        19.2186222 , -31.16586592,   8.98369938])

In [19]:
enet_model.intercept_

-6.465955602113581

# tahmin 

In [21]:
enet_model.predict(x_train)[:10]

array([325.74706292, 776.06632333, 522.86508419, 107.64091955,
       449.03139566, 997.76095723,  99.78828622, 311.33763086,
       418.50335021, 879.9502608 ])

In [24]:
enet_model.predict(x_test)[:10]

array([ 577.79111731,  617.33202224, 1031.39113156,  364.95861575,
        489.51894393,  300.74185842,  604.522666  ,  465.34678732,
        901.44473965,  703.20357123])

In [25]:
y_pred = enet_model.predict(x_test)

In [26]:
np.sqrt(mean_squared_error(y_test , y_pred))

357.1676548181246

In [28]:
r2_score(y_test ,y_pred)

0.41070222469326867

#model turning 

In [ ]:
enet_cv_model = ElasticNetCV(cv = 10)