# numpy sabit veri tiplidi , bundan dolayı DataFrame kullanılır 

In [2]:
import numpy as np 
import pandas as pd

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
df = pd.DataFrame(data = arr ,columns = ["Column1"])

In [6]:
df

Column1
0        0
1        1
2        2
3        3
4        4
5        5
6        6
7        7
8        8
9        9

In [7]:
df.size

10

In [8]:
df.head(4)

Column1
0        0
1        1
2        2
3        3

In [9]:
df.tail(3)

Column1
7        7
8        8
9        9

In [10]:
arr2 = np.random.randint(10 , size = 9).reshape(3,3)

In [11]:
arr2

array([[8, 9, 5],
       [8, 6, 5],
       [7, 1, 5]])

In [12]:
df2 = pd.DataFrame(data = arr2 , columns= ["Column1" ,"Column2" ,"Column2"]
                   ,index =["index1" ,"index2" ,"index3"])

In [13]:
df2

Column1  Column2  Column2
index1        8        9        5
index2        8        6        5
index3        7        1        5

In [14]:
df2.values

array([[8, 9, 5],
       [8, 6, 5],
       [7, 1, 5]])

In [15]:
type(df2.values)

numpy.ndarray

In [18]:
type(df2)

pandas.core.frame.DataFrame

In [19]:
#not = sadece verileri çekilirsa dataFrame , numpy array'ine dönüşür

In [20]:
"index1" in df2

False

In [21]:
"Column1" in df2

True