In [2]:
import pandas as pd 
df = pd.read_csv("original.csv")
df = df.iloc[: , 1 :len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
x =  df.drop("sales" ,axis=1)
y = df[["sales"]]

In [4]:
x


TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [5]:
y

sales
0     22.1
1     10.4
2      9.3
3     18.5
4     12.9
..     ...
195    7.6
196    9.7
197   12.8
198   25.5
199   13.4

[200 rows x 1 columns]

In [6]:
# Statsmodels ile model kurmak
import statsmodels.api as sm

In [7]:
lm = sm.OLS(y ,x)

In [9]:
model = lm.fit()

In [12]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Sun, 22 Mar 2020   Prob (F-statistic):                   2.43e-171
Time:                        20:14:52   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [13]:
#scikit learn ile model kurma

In [15]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [17]:
model = lm.fit(x ,y )

In [19]:
model.intercept_

array([2.93888937])

In [20]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

# Tahmin 


In [ ]:
# Sales = 2.94 + tv *0.04  + radio *0.19 - newspaper *0.001 

In [22]:
2.94 + 30 * 0.004 + 10 *0.19 - 40 *0.001

4.92

In [24]:
yeni_veri = [[30] ,[10] ,[40]]


In [26]:
import pandas as pd 
yeni_Veri = pd.DataFrame(yeni_veri)

In [27]:
yeni_Veri

0
0  30
1  10
2  40

In [28]:
yeni_veri = pd.DataFrame(yeni_veri).T

In [29]:
yeni_veri

0   1   2
0  30  10  40

In [48]:
model.predict(yeni_veri)

array([[6.15562918]])

In [37]:
from sklearn.metrics import mean_squared_error


In [42]:
MSE = mean_squared_error(y ,model.predict(x)) #hata kareler otalaması 
# y = gerçek değer , model.predict(x) = x 'lerin tahmin degeri'

In [43]:
model.predict(x)[:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [44]:
import numpy as np
RMSE = np.sqrt(MSE)
#Hata kareler ortalamasının karekökü

In [45]:
RMSE

1.6685701407225697

In [46]:
y

sales
0     22.1
1     10.4
2      9.3
3     18.5
4     12.9
..     ...
195    7.6
196    9.7
197   12.8
198   25.5
199   13.4

[200 rows x 1 columns]

In [47]:
x

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [50]:
#model.predict(x)

# Model doğrulama

In [51]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [52]:
x.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [53]:
# sinama seti 
from sklearn.model_selection import train_test_split


In [54]:
x_train , x_test , y_train ,y_test = train_test_split(x , y ,test_size = 0.20 ,random_state = 99)

In [56]:
x_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [57]:
y_train.head()

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [61]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
model = lm.fit(x_train ,y_train)

In [62]:
# EGİTİM HATASI
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_train ,model.predict(x_train))) # 

1.7236824822650751

In [65]:
# TEST HATASI
np.sqrt(mean_squared_error(y_test , model.predict(x_test)))

1.4312783138301641

In [66]:
# K -KATLI CV (capraz doğrulama yöntemi)

In [67]:
from sklearn.model_selection import cross_val_score

In [75]:
#cv MSE
MSE_CV = -cross_val_score(model , x_train , y_train ,cv = 10 ,scoring = "neg_mean_squared_error")
# cv = kaç parça ile test edileceği , scoring = hata karelerinin ortalamasının alınacağını söyledik
MSE_CV 

array([2.1019073 , 2.48953197, 3.09704214, 2.34694216, 3.68175761,
       1.8691401 , 3.18173007, 4.1927349 , 2.17128376, 8.03821974])

In [76]:
# cv RMSE
RMSE_CV = np.sqrt(-cross_val_score(model , x_train , y_train ,cv = 10 ,scoring = "neg_mean_squared_error"))
RMSE_CV

array([1.44979561, 1.57782508, 1.75984151, 1.53197329, 1.91879066,
       1.36716499, 1.78374047, 2.04761688, 1.47352766, 2.83517543])

In [77]:
np.mean(MSE_CV)

3.317028974234124

In [78]:
np.mean(RMSE_CV)

1.774545157598883