In [1]:
import numpy as np

In [9]:
arr1 = np.random.randint(1,10 ,size=10)

In [10]:
arr1

array([3, 8, 3, 4, 4, 1, 5, 7, 5, 7])

In [13]:
np.sort(arr1) #arr1 i sıralar ama atamadan değiştirmez

array([1, 3, 3, 4, 4, 5, 5, 7, 7, 8])

In [12]:
arr1

array([3, 8, 3, 4, 4, 1, 5, 7, 5, 7])

In [17]:
arr1.sort() # arr1 i sıralar ve atama işlemini yapar

In [18]:
arr1

array([1, 3, 3, 4, 4, 5, 5, 7, 7, 8])

In [ ]:
# normal = (ortalaması ,standartSapma , (boyut))

In [19]:
arr2 = np.random.normal(25,6 ,(4,3))

In [21]:
np.sort(arr2 ,axis = 0) #satirlarii kendi arasında sıralar

array([[18.03824651, 18.05472354, 22.12928556],
       [23.22893032, 18.54045537, 23.90591768],
       [25.08398761, 20.01471388, 26.8148125 ],
       [28.01529916, 24.57714347, 32.11938538]])

In [22]:
np.sort(arr2 ,axis=1) #sutunları kendi arasında sıralar

array([[18.03824651, 18.05472354, 26.8148125 ],
       [22.12928556, 24.57714347, 25.08398761],
       [18.54045537, 23.90591768, 28.01529916],
       [20.01471388, 23.22893032, 32.11938538]])