In [1]:
import numpy as np

# tek boyutlu 

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# arr dizisini 3 e kadar bir böl , 3den beşe kadar bir böl

In [8]:
split1 = np.split(arr , [3 ,5])

In [9]:
split1

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]

# iki boyutlu

In [11]:
arr2 = np.arange(1,10).reshape((3,3))

In [12]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# VerticalSplit

In [15]:
split2V = np.split(arr2 ,[2])

In [16]:
split2V

[array([[1, 2, 3],
        [4, 5, 6]]), array([[7, 8, 9]])]

In [27]:
ust ,alt = np.vsplit(arr2 ,[2]) # burda dizileri ayrıştırdık üst alt diye

In [28]:
ust 

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
alt

array([[7, 8, 9]])

# HorizonalSplit

In [33]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
sag ,sol = np.hsplit(arr2 ,[2])

In [31]:
sag 

array([[1, 2],
       [4, 5],
       [7, 8]])

In [32]:
sol

array([[3],
       [6],
       [9]])