In [1]:
import numpy as np 

# tek boyutlu 

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[1]

2

In [5]:
arr[2]

3

In [7]:
arr[5]

6

In [8]:
arr[[1,2 ,5]]

array([2, 3, 6])

In [9]:
index_info = [1,2 ,5]

In [10]:
arr[index_info]

array([2, 3, 6])

In [11]:
arr[index_info] = [0 ,1 ,3]

In [12]:
arr

array([1, 0, 1, 4, 5, 3, 7, 8, 9])

# iki boyutlu arraylarde Fancy

In [18]:
arr2 = np.arange(9).reshape((3,3))

In [20]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# normal index ile  erişim

In [21]:
arr2[0]

array([0, 1, 2])

# Fancy index ve normal index birlikte kullanarak erişim

In [28]:
arr2[1 , [1,2]]

array([4, 5])

# slince index ile erişim

In [26]:
arr2[0:2 ,:]

array([[0, 1, 2],
       [3, 4, 5]])

# Fancy index ile silince indexi beraber kulllanarak erişim erişim

In [25]:
arr2[2: ,[1,2] ]

array([[7, 8]])

In [ ]:
a