In [1]:
import numpy as np 


In [2]:
arr1 = np.random.normal(10 ,5 ,size= 10)

In [3]:
arr1

array([10.5672732 , 11.5500712 , 11.67534422,  4.7418629 , 12.04280011,
       10.32681001, 10.05501541, 12.41809026, 15.54447893, 10.82334101])

In [6]:
arr1 > 10.3


array([ True,  True,  True, False,  True,  True, False,  True,  True,
        True])

In [7]:
arr1[arr1 > 10.3]

array([10.5672732 , 11.5500712 , 11.67534422, 12.04280011, 10.32681001,
       12.41809026, 15.54447893, 10.82334101])