In [1]:
import numpy as np

# tek boyut

In [6]:
a = np.arange(20 ,30)

In [4]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
a[:3]

array([20, 21, 22])

In [8]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [10]:
a[5::3]

array([25, 28])

# iki boyutlu  [satır seç , sutun seç]


In [15]:
b = np.random.randint(0 ,10 ,size=(5,5))

In [16]:
b

array([[9, 6, 9, 8, 9],
       [9, 6, 2, 3, 5],
       [6, 0, 8, 4, 0],
       [0, 3, 7, 9, 8],
       [0, 5, 9, 9, 2]])

In [18]:
b[0]

array([9, 6, 9, 8, 9])

In [19]:
b[3]

array([0, 3, 7, 9, 8])

In [21]:
b[:,3]# tüm satırları al 3. sutunu getir

array([8, 3, 4, 9, 9])

In [23]:
b[0:2 ,2:4]

array([[9, 8],
       [2, 3]])