In [2]:
import numpy as np

# Numpy arraylarinin oluşturulması 

In [2]:
np.array([1 ,2 ,3 ,4 ,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1 ,3 , 5 ,7 ,8] , dtype="float32")

array([1., 3., 5., 7., 8.], dtype=float32)

In [4]:
np.arange(1 ,10 ,2) # 1'den 10' a kadar 2 şer 2 şer artan numpy arayı oluşturur

array([1, 3, 5, 7, 9])

In [5]:
np.eye((3)) # 3' e 3'lük 2 boyutlu birim matrix oluşturur

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.zeros(10) # tek boyutlu sıfırlardan oluşan numpy arayı oluşturur

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((2, 8)) # iki boyutlu 2 satır 8 sutundan oluşan numpy arayı oluşturur

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.ones((3 ,5)) # bir'lerden oluşan 2 boyutlu array oluşturur

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.linspace(0,1 ,20) # 0 ,ile 1 arasında 20 tane değer oluşturur

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [10]:
np.random.normal(0 ,1  ,30) # ortalaması 0 , varyansı 1 olan 30 tane değer oluşturur

array([-0.28427721, -1.19847326,  0.17808901,  1.0501298 ,  0.5873279 ,
        1.88434713, -0.18284771,  0.36269913,  1.03764334,  0.76669567,
        0.1645115 ,  0.94066094,  0.5863614 , -0.64414557, -0.86053197,
        0.99468848, -2.25502076, -0.10714411, -1.20639167,  0.63197896,
        1.30825882, -0.01894394,  0.2050332 ,  0.1764565 ,  0.43944087,
        0.23327036,  1.54265203, -0.88910096, -0.82178955, -0.01235059])

In [11]:
np.random.randint(0 ,10 ,15) # 0 ile 10 arasında 15 tane sayı oluştur

array([5, 3, 0, 9, 2, 0, 5, 7, 4, 6, 3, 3, 7, 5, 8])

# Numpy Biçimlendirme

In [12]:
# ndim : boyut sayısı
# shape : boyut bilgisi
# size : boyut (toplam eleman sayısı)
# dtype : data tipi

In [21]:
a = np.random.randint(2 ,10 ,size = (10))

In [22]:
a

array([9, 9, 6, 2, 8, 7, 8, 7, 7, 9])

In [23]:
a.shape

(10,)

In [24]:
a.ndim

1

In [25]:
a.size

10

In [27]:
a.dtype

dtype('int32')

In [30]:
a = np.random.randint(10,20 ,size = (2,3))

In [31]:
a

array([[13, 16, 19],
       [18, 13, 12]])

In [32]:
a.shape

(2, 3)

In [33]:
a.ndim

2

In [34]:
a.size

6

In [36]:
a.dtype

dtype('int32')

In [37]:
## Yeniden biçimlendirme işlemleri (Reshape ) // vektörden matrix olşturma işlemeleri

In [39]:
arr = np.arange(1,10)

In [41]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr.reshape(3,3) # arrayımızı 3 satır 3 sutun olacak şekilde vektörden matrixe dönüştürüyoruz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2 = np.array([1 ,2 ,3])

In [45]:
arr2

array([1, 2, 3])

In [46]:
arr2.reshape(1 ,3)

array([[1, 2, 3]])

In [47]:
arr2.reshape(3,1)

array([[1],
       [2],
       [3]])

In [48]:
# bir başka reshape yöntemi 

In [49]:
arr2

array([1, 2, 3])

In [50]:
arr2[np.newaxis ,:] #satır bazında

array([[1, 2, 3]])

In [51]:
arr2[: ,np.newaxis] # sutun bazında

array([[1],
       [2],
       [3]])

In [54]:
arr2[np.newaxis , np.newaxis] #merak ettim denedim :)

array([[[1, 2, 3]]])

# Array Birleştirme İşlemleri

## tek boyutlarda birleştirme

In [73]:
arr1 = np.array([1 ,2 ,3])
arr2 = np.array([4 ,5 ,6])

In [74]:
np.concatenate([arr1 ,arr2]) #satır bazınde tek boyutlu birleştirme

array([1, 2, 3, 4, 5, 6])

In [76]:
np.concatenate([arr1 , arr2] ,axis = 1) 
#tek boyutlu arrayler concatenate ile birleştirilerek çok boyutlu olup sutunsal olarak birleştirilmez

AxisError: axis 1 is out of bounds for array of dimension 1

In [77]:
arr3 = np.array([7 ,8 ,9])

In [78]:
np.concatenate([arr1 , arr2 ,arr3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## iki boyutlu arraylerde birleştirme 

In [80]:
arr1 = np.array([[1 ,2 ,3],
                [4 ,5 ,6]])

arr2 = np.array([[7 ,8, 9] ,
                [10 ,11 ,12]])

In [82]:
np.concatenate([arr1 ,arr2])
# alt alta gelecek şekilde birleştirme

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [84]:
np.concatenate([arr1 , arr2] ,axis = 1)
# yan yana gelecek şekilde 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## Birbirlerinden farklı boyutlu arraylerde birleştirme işlemi 

In [86]:
arr1 = np.array([1 ,2 ,3])

arr2 = np.array([[4 ,5 ,6],
                [7 ,8, 9]])

In [90]:
np.vstack((arr1 ,arr2)) 
# vertical birleştirme yanı dikey olarak


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
np.hstack((arr1 ,arr2)) 
# satır boyları eşit olmadığı için yatay birleştirme işlemi yapılamadı 

ValueError: all the input arrays must have same number of dimensions

In [94]:
arr3 = np.array([[10 ,11 ,12] ,
                [13 ,14 ,15]])

In [96]:
np.hstack((arr2 ,arr3)) 
# horizonal birleştirme yani yatay olarak birleştirir her satırı kendi eşteniği ile birleştirir

array([[ 4,  5,  6, 10, 11, 12],
       [ 7,  8,  9, 13, 14, 15]])

## array ayırma işlemleri 

In [ ]:
# tek boyutlulularda

In [106]:
x = [1 ,2 ,3 ,4 ,5 ,6 ,7 ,8, 9]


SyntaxError: invalid syntax (<ipython-input-107-79eab1209574>, line 1)

In [108]:
np.split(x ,[4, 7])

[array([1, 2, 3, 4]), array([5, 6, 7]), array([8, 9])]

In [109]:
x = np.array(x)

In [110]:
np.split(x ,[4, 7])

[array([1, 2, 3, 4]), array([5, 6, 7]), array([8, 9])]

In [123]:
np.split(x ,[1] ,axis = 1 ) 
#tek boyutlularda axis verilmez

IndexError: tuple index out of range

In [ ]:
# cok boyutlularda

In [112]:
arr1 = np.array([[1 ,2, 3, 4],
                 [5 ,6 ,7 , 8],
                 [9 ,10 ,11 ,12],
                 [13 ,14 ,15 ,16]
                ])

In [124]:
np.split(arr1 ,[4 ,7])
# dördüncü satıra kadar alır yani tüm satırları almış olur bu sebeple diğer değerler boş değerdir

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32)]

In [120]:
np.split(arr1 , [2] ) 
# dikeyde bir bölme işlemi uygulanır

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [119]:
np.split(arr1 ,[2] ,axis = 1) 
# yatayda bir bölme işlemi uygulanır 

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [125]:
# yukarda yapılan işlemleri farklı bir altarnatifi vardir örneğin ; 

In [126]:
arr1 = np.array([[1 ,2, 3, 4],
                 [5 ,6 ,7 , 8],
                 [9 ,10 ,11 ,12],
                 [13 ,14 ,15 ,16]
                ])

In [135]:
ust , alt  = np.vsplit(arr1 , [2])

In [138]:
ust

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [139]:
alt

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [140]:
# şimdide bunları yanyana birleştirelim 


In [142]:
np.concatenate((ust,alt)) # dikey olarak birleştirdik

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [145]:
np.concatenate((ust ,alt) ,axis = 1)  #yatay olarak satırları aralarında birleştirdik

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [146]:
# örnek 2 

In [149]:
sol ,sag = np.hsplit(arr1 ,[2])

In [150]:
sol

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [151]:
sag

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [153]:
np.concatenate((sol ,sag)) #alt alta birleştirdik

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [157]:
np.concatenate((sol ,sag) ,axis = 1) # bu şekilde ilk halimizi elde etmiş olduk

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# Numpy Arraylerini Sıralamak 

In [158]:
arr = np.array([2 , 1 ,5 ,4, 6, 3, 7])

In [159]:
arr.sort()
# sıralama işlemini yapar ve kaydeder bunu direk değişkene uygular

In [160]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [161]:
arr = np.array([2 , 1 ,5 ,4, 6, 3, 7])

In [167]:
np.sort(arr)
# sıralama işlemini yapar (metot işlemi ile ) ve kaydetmez , kaydetmek için atama bekler

array([1, 2, 3, 4, 5, 6, 7])

In [168]:
arr

array([2, 1, 5, 4, 6, 3, 7])

In [169]:
arr_s = np.sort(arr )

In [171]:
arr_s

array([1, 2, 3, 4, 5, 6, 7])

In [176]:
arg_s =  np.argsort(arr) 
# argsort fonksiyonu sıralandığındaki değerlerin gerçek arrayde kaçıncı indexde olduğunu belirtir


In [177]:
arg_s

array([1, 0, 5, 3, 2, 4, 6], dtype=int64)

In [174]:
arr

array([2, 1, 5, 4, 6, 3, 7])

In [178]:
arr[arg_s]

array([1, 2, 3, 4, 5, 6, 7])

In [179]:
# yukarda görüldüğü gibi index secerek sıralı getirme işlemi yapabliriz 

# INDEXX İŞLEMLERİ 

In [1]:
import numpy as np 

In [2]:
arr = np.arange(20,30)

In [3]:
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
arr2 = np.arange(0 ,16).reshape(4,4)

In [16]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## normal index 

In [6]:
arr[3]

23

In [17]:
arr2[3]

array([12, 13, 14, 15])

In [18]:
arr2[3,2] 
#arr2 nin 3.satır ikinci elemanı

14

## slince index

In [5]:
arr[2::2] #2. indexten başla 2şer ikişer git

array([22, 24, 26, 28])

In [20]:
arr2[3: ,2:] 
# arr2 nin 3.satırdan sonrasındaki satırların 2.elemeanından sonraki elemanlar

array([[14, 15]])

In [21]:
# alt küme seçilip bunun üzerinde  değişiklik yapılırsa ana kümeyide etkiler

In [48]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
alt_kume2 = arr2[2:3,2:]

In [53]:
alt_kume2

array([[10, 11]])

In [57]:
alt_kume2[0,0] = 3

In [59]:
arr2 # görüldüğü gibi 10 değerinin yerini 3 aldı


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9,  3, 11],
       [12, 13, 14, 15]])

## fancy index

In [61]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9,  3, 11],
       [12, 13, 14, 15]])

In [74]:
al_getir = [1,3]


In [75]:
arr2[al_getir]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [82]:
al_getir2 =[[1,3]]

In [83]:
arr2[al_getir2]
#1.satır ve 3.sutunu getirir ama biz 1.satırdaki 3.elemana erişmek istiyoruz 

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [88]:
# bunun için 
al_getir3 = [[1] , [3]]

In [89]:
# böyle yapmalıyız 
arr2[al_getir3]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([7])

In [90]:
# veya  bu şekilde yapmalıyız

satir = np.array([1])
sutun = np.array([3])


In [91]:
arr2[satir , sutun]

array([7])

In [100]:
# yada  bu şekilde kullaılabilir
arr2[1, [2,3]]

array([6, 7])

# Koşullu eleman işlemleri 

In [105]:
arr = np.random.randint(1 ,10 ,size = (4,5))

In [106]:
arr

array([[4, 6, 3, 1, 4],
       [1, 5, 3, 3, 6],
       [2, 8, 4, 9, 2],
       [9, 4, 3, 3, 6]])

In [107]:
arr > 3

array([[ True,  True, False, False,  True],
       [False,  True, False, False,  True],
       [False,  True,  True,  True, False],
       [ True,  True, False, False,  True]])

In [108]:
arr <3

array([[False, False, False,  True, False],
       [ True, False, False, False, False],
       [ True, False, False, False,  True],
       [False, False, False, False, False]])

In [110]:
np.equal(3 , arr) #üç olan değerleri true yap 

array([[False, False,  True, False, False],
       [False, False,  True,  True, False],
       [False, False, False, False, False],
       [False, False,  True,  True, False]])

In [119]:
np.equal([0 ,1 ,3],  np.arange(3))
# içinde bu değerlerden herhangi biri var mı 

array([ True,  True, False])

In [124]:
np.equal([0 ,1 ,2] ,arr )
# 2 boyutlu arraylerde boyle bir işlem yapılamıyor

ValueError: operands could not be broadcast together with shapes (3,) (4,5) 

In [125]:
arr2 = np.arange(10 )

In [126]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
np.sum(arr2 > 3)
#arr2 nin içinde 3 den buyuk olanların sayısını getirir

6

In [130]:
np.sum(arr2 < 3)

3

In [135]:
np.sum(arr == 1 )
# toplam 1 e eşit index sayısını getirir

2

In [137]:
np.sum(arr ==1 , axis = 1) 
# satırlarda 1 e eşit olan indexlerin sayısını getirir


array([1, 1, 0, 0])

In [139]:
np.sum(arr == 1 , axis = 0)
# arr2 nin içinden sutunlardaki 1 sayısını getirir

array([1, 0, 0, 1, 0])

In [140]:
arr

array([[4, 6, 3, 1, 4],
       [1, 5, 3, 3, 6],
       [2, 8, 4, 9, 2],
       [9, 4, 3, 3, 6]])

In [141]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
np.all(arr2 > 3)
#arr2 nin tüm elemanları 3 mu ?

False

In [148]:

np.any(arr2 > 3 ) 
# arr2 nin en az bir elemanı 3 mu ? 

True

In [149]:
np.all(arr > 3)
#arr nin tüm elemanları 3 mu ? 

False

In [153]:
np.any(arr == 3 , axis = 1) 
# arr içerisinde en az 1 tane içinde  3  olan satırlar hangileri 

array([ True,  True, False,  True])

In [160]:
a = np.any(arr == 3 ,axis = 0 )
#arr içinde en az 1 tane 3 olan sutun hangileri 

In [161]:
a

array([False, False,  True,  True, False])

In [164]:
arr[:,a] # arr içinden içinde 3 olan sutunları getirir :)

array([[3, 1],
       [3, 3],
       [4, 9],
       [3, 3]])

# matematiksel işlemler 

In [169]:
arr = np.random.normal(0 ,1 ,size = (3,5))

np.mean  = ortalama 
np.std = standart sapma
np.var = varyansı 
np.median = medyanı 

ayrıca bunların başına "na" koyarak na değerlere duyarlı hale getirilebilir 

In [170]:
arr

array([[ 0.50107084,  1.58882867,  0.26398995,  0.17055118,  0.10319095],
       [-0.73442292, -2.28965772,  1.79738053,  0.49923393,  0.57702078],
       [-1.15459079, -0.56012081,  0.39428829, -1.55875476,  1.62442173]])

In [171]:
np.mean(arr) 
# arr nın tümünün ortalaması 

0.08149532293106734

In [172]:
np.std(arr)

1.1328626722972295

In [173]:
np.var(arr)

1.28337783428442

In [174]:
np.median(arr)

0.26398995343718584

In [175]:
np.mean(arr , axis = 0)  
# arr nın sütünlarının ortalaması

array([-0.46264762, -0.42031662,  0.81855292, -0.29632322,  0.76821115])

In [176]:
np.mean(arr ,axis = 1 )
# arr nın satırlarının ortalaması

array([ 0.52552632, -0.03008908, -0.25095127])

# Array birleştirme (Brodcasting)

Kural 1 = Array boyutları eşitlenir 
Kural 2 = Satır ve sutun sayıları eşitlenir (ancak sadece abşlangıc değeri 1 ise)
Kural 3 = Hala uyuşmazlık varsa hata oluşur 

In [179]:
arr1 = np.eye(3)

In [181]:
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [183]:
arr2 = np.arange(3)

In [184]:
arr2

array([0, 1, 2])

In [185]:
arr1 + arr2

array([[1., 1., 2.],
       [0., 2., 2.],
       [0., 1., 3.]])

In [186]:
arr3 = np.arange(3)
arr4 = np.arange(3)[:,np.newaxis]

In [187]:
arr3 

array([0, 1, 2])

In [188]:
arr4

array([[0],
       [1],
       [2]])

In [189]:
arr3 + arr4

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [190]:
# hatalı işlem 


In [193]:
arr5 = np.ones((3,2))
arr6 = np.arange(3)

In [197]:
arr5.shape
# sutun boyutu arraylerin copy işleminde tekrarlanma olamayacağından dolayı hata alır

(3, 2)

In [198]:
arr6.shape

(3,)

In [199]:
arr5 + arr6 

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

## Yapısal Numpy arrayleri 

In [200]:
isim = ["Ali" ,"Veli" ,"Elli"]
yas = [25 , 22 ,19]
boy = [168 ,159 ,172]

In [201]:
data = np.zeros(3 , dtype = {
    "names" : ["isim" ,"yas" ,"boy"],
    "formats" :["U10" ,"i4" ,"f8"]
})

In [202]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [203]:
data["isim"] = isim 
data["yas"] = yas
data["boy"] = boy

In [206]:
data

array([('Ali', 25, 168.), ('Veli', 22, 159.), ('Elli', 19, 172.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [207]:
data[0]

('Ali', 25, 168.)

In [208]:
data["isim"]

array(['Ali', 'Veli', 'Elli'], dtype='<U10')

In [209]:
data[data["yas"] < 25]["isim"]

array(['Veli', 'Elli'], dtype='<U10')

In [210]:
#gruoup by gibi sorgular yapılamayacağından dolayı pandas kutuphanesine ihtiyaç duyulmuştur

In [13]:
import pandas as pd 
import numpy as np

v1 = np.random.randint(0,10 ,size = 5)
v2 = np.random.randint(0 ,10 ,size = 5)
v3 = np.random.randint(0 ,10 ,size = 5)

sozluk = {
    "var1" : v1,
    "var2" : v2,
    "var3" : v3
}


df = pd.DataFrame(sozluk ,index = ["a" ,"b" ,"c" ,"d" ,"e"])

In [4]:
df

var1  var2  var3
a     0     1     3
b     2     2     4
c     7     4     7
d     7     1     2
e     6     3     0

In [5]:
df["a" : "c"]

var1  var2  var3
a     0     1     3
b     2     2     4
c     7     4     7

In [6]:
df.drop("b") 
#inplace = True yakılmazsa df de değişiklik yapılmaz

var1  var2  var3
a     0     1     3
c     7     4     7
d     7     1     2
e     6     3     0

In [8]:
df.drop("var3" ,axis = 1)
# column bazında silme işlemi yapabilmek için axis = 1 yaptık

var1  var2
a     0     1
b     2     2
c     7     4
d     7     1
e     6     3

In [15]:
df.drop("e" ,inplace = True)
df
# inplace argumanı True olduğu için işlem geçerli kılındı

KeyError: "['e'] not found in axis"

In [17]:
"var1" in df
# df nin içinde var 1 var mı


True

In [21]:
"a" in df
#indexlerde arama yapmaz

False

In [23]:
df["var1"] is df["var1"]
# df içindeki var1 sutunu var1 sutununa eşit mi ?

True

In [24]:
l = ["var1" ,"var2" ,"var4"]

for i in l:
    print(i in df)

True
True
False


In [25]:
liste = ["var1" ,"var2"]
df[liste]

var1  var2
a     8     0
b     4     5
c     6     7
d     3     2

In [26]:
df.drop(liste, axis = 1)

var3
a     4
b     1
c     2
d     3

 Loc ve iLoc işlemleri

In [27]:
df

var1  var2  var3
a     8     0     4
b     4     5     1
c     6     7     2
d     3     2     3

In [28]:
df[0:3]

var1  var2  var3
a     8     0     4
b     4     5     1
c     6     7     2

In [29]:
df[0:3 ,"var1" ,"var2"]
# iki boyutlu sorgulama yaptığımız zaman loc ve iloc işin içine girer

TypeError: '(slice(0, 3, None), 'var1', 'var2')' is an invalid key

In [30]:
df.loc["a" : "c" ,  "var1" : "var2"]

var1  var2
a     8     0
b     4     5
c     6     7

In [31]:
df.iloc[0:3 , 0 : 2]

var1  var2
a     8     0
b     4     5
c     6     7

In [33]:
df[df.var1 > 5 ]
# df içinde var1 i 5 den buyuk olan tüm satırları getir

var1  var2  var3
a     8     0     4
c     6     7     2

In [35]:
df[df.var1 > 5 ]["var1"]
# df içinde var1 de 5 ten butuk olan satırları geitr

a    8
c    6
Name: var1, dtype: int32

In [37]:
df.loc[df.var1 > 5 ,["var1"]]
#yukardaki işlemin farklı kullanımı ve df halinde getirilmişi

var1
a     8
c     6

## birleştirme işlemleri

In [38]:
df

var1  var2  var3
a     8     0     4
b     4     5     1
c     6     7     2
d     3     2     3

In [39]:
df2 = df + 99

In [40]:
df2

var1  var2  var3
a   107    99   103
b   103   104   100
c   105   106   101
d   102   101   102

In [42]:
pd.concat([df , df2]) 
#alt alta birleştirme

var1  var2  var3
a     8     0     4
b     4     5     1
c     6     7     2
d     3     2     3
a   107    99   103
b   103   104   100
c   105   106   101
d   102   101   102

In [44]:
pd.concat([df ,df2] ,axis = 1)
# yan yana birleştirme

var1  var2  var3  var1  var2  var3
a     8     0     4   107    99   103
b     4     5     1   103   104   100
c     6     7     2   105   106   101
d     3     2     3   102   101   102

In [46]:
pd.concat([df ,df2] ,ignore_index = True)
# indexleri default olarak ata 

var1  var2  var3
0     8     0     4
1     4     5     1
2     6     7     2
3     3     2     3
4   107    99   103
5   103   104   100
6   105   106   101
7   102   101   102

## ileri birleştirme işlemleri Merge ve Join 

In [47]:
df

var1  var2  var3
a     8     0     4
b     4     5     1
c     6     7     2
d     3     2     3

In [48]:
df2

var1  var2  var3
a   107    99   103
b   103   104   100
c   105   106   101
d   102   101   102

In [52]:
pd.concat([df ,df2])

var1  var2  var3
a     8     0     4
b     4     5     1
c     6     7     2
d     3     2     3
a   107    99   103
b   103   104   100
c   105   106   101
d   102   101   102

In [53]:
pd.concat([df ,df2] ,ignore_index = True)

var1  var2  var3
0     8     0     4
1     4     5     1
2     6     7     2
3     3     2     3
4   107    99   103
5   103   104   100
6   105   106   101
7   102   101   102

In [54]:
df2.columns 

Index(['var1', 'var2', 'var3'], dtype='object')

In [55]:
df2.columns = ["var1" ,"var2" ,"değ1"]

In [56]:
pd.concat([df ,df2])
# df lerde değerlerin eşteniği olmadığı içi nan olarak atandı

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


değ1  var1  var2  var3
a    NaN     8     0   4.0
b    NaN     4     5   1.0
c    NaN     6     7   2.0
d    NaN     3     2   3.0
a  103.0   107    99   NaN
b  100.0   103   104   NaN
c  101.0   105   106   NaN
d  102.0   102   101   NaN

In [58]:
pd.concat([df , df2] ,join = "inner")
#eğer joini inner yaparsa ikisindede ortak olan değerler gelir

var1  var2
a     8     0
b     4     5
c     6     7
d     3     2
a   107    99
b   103   104
c   105   106
d   102   101

In [60]:
pd.concat([df ,df2] ,join_axes = [df.columns])
# join axes ile df in sutunlarına göre birleştirme yaptık

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  """Entry point for launching an IPython kernel.


var1  var2  var3
a     8     0   4.0
b     4     5   1.0
c     6     7   2.0
d     3     2   3.0
a   107    99   NaN
b   103   104   NaN
c   105   106   NaN
d   102   101   NaN

Merge join

In [63]:
df1 = pd.DataFrame(
    {
        "calisanlar" : ["Ali" ,"Veli" ,"Ayse" ,"Fatma"],
        "grup" : ["Muhasebe" ,"Muhendislik" ,"Muhendislik", "IK"] 
    }
)
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           IK

In [64]:
df2 = pd.DataFrame(
    {
        "calisanlar" : ["Veli" ,"Ali" ,"Ayse" ,"Fatma"],
        "ilk_giris" :[2001 ,2004 ,2003 ,2017]
        
    }
)

df2

calisanlar  ilk_giris
0       Veli       2001
1        Ali       2004
2       Ayse       2003
3      Fatma       2017

In [66]:
df4 = pd.DataFrame(
    {
        "grup" : ["Muhasebe" ,"IK" ,"Muhendislik"],
        "mudur" : ["Caner" ,"Mustafa" ,"Berkcan"]
    }

)
df4

grup    mudur
0     Muhasebe    Caner
1           IK  Mustafa
2  Muhendislik  Berkcan

In [67]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           IK

In [68]:
df2

calisanlar  ilk_giris
0       Veli       2001
1        Ali       2004
2       Ayse       2003
3      Fatma       2017

In [71]:
pd.merge(df1 ,df2)
# kendisi ortak sutunu bulup birleştirme işlemini yapar dilersek kendimizde atayabliriz

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2004
1       Veli  Muhendislik       2001
2       Ayse  Muhendislik       2003
3      Fatma           IK       2017

In [3]:
import pandas as pd 
pd.merge(df1 ,df2 )

NameError: name 'df1' is not defined

In [4]:
pd.merge(df1 ,df2 ,on = "calisanlar")
# calsanlar grubunu esas olarak birleştirme işlemi yaptık

NameError: name 'df1' is not defined